-- Execute once at a time with a role allowed to create these lab objects.
-- No credentials or user grants are stored here. No CREATE OR REPLACE on data.
CREATE WAREHOUSE IF NOT EXISTS NYC_TAXI_WH
    WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;
USE WAREHOUSE NYC_TAXI_WH;
CREATE DATABASE IF NOT EXISTS NYC_TAXI;
USE DATABASE NYC_TAXI;
CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS BRONZE;
CREATE SCHEMA IF NOT EXISTS SILVER;
CREATE SCHEMA IF NOT EXISTS GOLD;
USE SCHEMA RAW;
CREATE STAGE IF NOT EXISTS TAXI_PARQUET FILE_FORMAT = (TYPE = PARQUET);
CREATE TABLE IF NOT EXISTS YELLOW_TRIPS (
    PAYLOAD VARIANT NOT NULL,
    SOURCE_FILE VARCHAR NOT NULL,
    SOURCE_MONTH VARCHAR NOT NULL,
    SOURCE_SHA256 VARCHAR NOT NULL,
    SOURCE_ROW NUMBER NOT NULL,
    LOADED_AT TIMESTAMP_TZ NOT NULL
);
CREATE TABLE IF NOT EXISTS LOAD_MANIFEST (
    SOURCE_MONTH VARCHAR NOT NULL,
    SHA256 VARCHAR NOT NULL,
    ROW_COUNT NUMBER NOT NULL,
    LOADED_AT TIMESTAMP_TZ NOT NULL
);
CREATE TABLE IF NOT EXISTS INGESTION_MUTEX (ID NUMBER NOT NULL, TOKEN NUMBER NOT NULL);
INSERT INTO INGESTION_MUTEX (ID, TOKEN)
SELECT 1, 0 WHERE NOT EXISTS (SELECT 1 FROM INGESTION_MUTEX WHERE ID = 1);
