-- Optional: an administrator runs this after bootstrap for an existing lab role.
-- Set only a role identifier here; do not add user passwords or private keys.
SET LAB_ROLE = 'NYC_TAXI_ROLE';
GRANT USAGE ON WAREHOUSE NYC_TAXI_WH TO ROLE IDENTIFIER($LAB_ROLE);
GRANT USAGE ON DATABASE NYC_TAXI TO ROLE IDENTIFIER($LAB_ROLE);
GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA NYC_TAXI.RAW TO ROLE IDENTIFIER($LAB_ROLE);
GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA NYC_TAXI.BRONZE TO ROLE IDENTIFIER($LAB_ROLE);
GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA NYC_TAXI.SILVER TO ROLE IDENTIFIER($LAB_ROLE);
GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA NYC_TAXI.GOLD TO ROLE IDENTIFIER($LAB_ROLE);
GRANT READ, WRITE ON STAGE NYC_TAXI.RAW.TAXI_PARQUET TO ROLE IDENTIFIER($LAB_ROLE);
GRANT SELECT, INSERT, DELETE ON TABLE NYC_TAXI.RAW.YELLOW_TRIPS TO ROLE IDENTIFIER($LAB_ROLE);
GRANT SELECT, INSERT, DELETE ON TABLE NYC_TAXI.RAW.LOAD_MANIFEST TO ROLE IDENTIFIER($LAB_ROLE);
GRANT SELECT, INSERT, DELETE ON TABLE NYC_TAXI.RAW.TAXI_ZONES TO ROLE IDENTIFIER($LAB_ROLE);
GRANT SELECT, UPDATE ON TABLE NYC_TAXI.RAW.INGESTION_MUTEX TO ROLE IDENTIFIER($LAB_ROLE);
